version: '3.7'

services:
 
  app:
    build: .
    ports: 
      - 8000:80
    volumes: 
      - ./www:/var/www/html
    links: 
      - db
    depends_on: 
      - db
  
  db:
    image: mysql:5.7.32
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: business-control
    ports:
      - 8001:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d